#!/usr/bin/env python3
from urllib import request
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
import numpy as np
import argparse
import datetime

name_list = ["USER NAME"]
name_list = sorted(name_list)

url = "http://www.lsnl.jp/cgi-bin/pytyping?id=lsnl-training&action=list"


def html_parse():
    # parse the html data
    html = request.urlopen(url)
    target = BeautifulSoup(html.read(), "lxml")
    text = target.get_text()
    lines = [line for line in text.splitlines()]
    return lines


def string_parse(lines):
    # all data is in review
    review = []
    for line in lines:
        line = str(line).replace("\t", " ").split()
        review.append(line)
    return review


def count_times(review):
    # count frequency of times
    names = []
    tmp = {}
    for line in review[:-2]:
        names.append(line[4])
    for name in name_list:
        tmp.update({name: names.count(name)})
    for i in sorted(tmp.items(), key=lambda x: x[1], reverse=True):
        print(i)


def plot_fig0(review):
    half_data = []
    week = str(datetime.date.today() -
               datetime.timedelta(days=6))
    review = sorted(review[:-1], key=lambda x: x[4])
    for count, i in enumerate(review):
        if(week < i[0]):
            half_data.append(i[0] + " " + i[4]+" "+i[6])
    return half_data


def plot_fig1(y):
    new_data = [line.split() for line in y]
    last_data = []
    last = []
    score = []
    date = new_data[0][0]
    name = new_data[0][1]
    sco = new_data[0][2]
    last_data.append(date+" "+name+" "+sco)
    for count, line in enumerate(new_data):
        if(new_data[count][0] != date):
            score.clear()
            score.append(line[2])
            date = line[0]
            name = line[1]
            last_data.append(line[0]+" "+line[1]+" "+max(score))
        else:
            if(new_data[count][1] != name):
                score.clear()
            date = line[0]
            name = line[1]
        score.append(line[2])
    return last_data


def plot_fig(last_data):
    print("option: set style data linespoints \nxlabel: date \nylabel: all score")
    for name in name_list:
        print("name: "+name)
        for count, data in enumerate(last_data):
            ldate, lname, lscore = data.split(" ")
            if(name == lname):
                print(int(ldate[-2:]), lscore)
        print()
    pass


def parsers():
    # option parses
    parser = argparse.ArgumentParser(description='Process some integers')
    parser.add_argument("-c", "--count",
                        action="store_true", help="show histogram of counts")
    parser.add_argument("-f", "--figure",
                        action="store_true", help="show figure of score")
    opt = parser.parse_args()
    return opt


def processing1():
    # process of opt.count
    lines = html_parse()
    review = string_parse(lines)
    count_times(review)


def processing2():
    # process of opt.figure
    lines = html_parse()
    review = string_parse(lines)
    half_data = plot_fig0(review)
    last_data = plot_fig1(half_data)
    plot_fig(last_data)


def main():
    opt = parsers()
    if(opt.count):
        processing1()
    elif(opt.figure):
        processing2()


main()
# www.lsnl.jp/~ohsaki/software/xdoplot/xdoplot
