#!/usr/local/bin/python3.7
import pyautogui
import sys
import os

path = os.getcwd()
val = sys.argv
x, y = pyautogui.size()
s = None
i = x / 2
if (val[1] == "-w"):
    s = pyautogui.screenshot()
elif (val[1] == "-r"):
    s = pyautogui.screenshot(region=(i, 0, i, y))
elif (val[1] == "-l"):
    s = pyautogui.screenshot(region=(0, 0, i, y))

s.save(path + "/" + "photo.png")
